test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.dex_domain="sub.domain.tld"
    args.dex_path="/example"