test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    preinstall = """
    sudo yunohost domain add dex.domain.tld
    sudo yunohost domain add minio.domain.tld
    """

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.dex_domain="dex.domain.tld"
    args.dex_path="/example"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.f56cd7d867a5d6ea42758f2d2c4de238565468f1.name = "Upgrade from 0.69.2"
    test_upgrade_from.f56cd7d867a5d6ea42758f2d2c4de238565468f1.args.language = "en"
    test_upgrade_from.f56cd7d867a5d6ea42758f2d2c4de238565468f1.args.domain = "domain.tld"
    test_upgrade_from.f56cd7d867a5d6ea42758f2d2c4de238565468f1.args.dex_domain = "dex.domain.tld"
    test_upgrade_from.f56cd7d867a5d6ea42758f2d2c4de238565468f1.args.minio_domain = "minio.domain.tld"
    test_upgrade_from.f56cd7d867a5d6ea42758f2d2c4de238565468f1.args.minio_admin = "package_checker"
    test_upgrade_from.f56cd7d867a5d6ea42758f2d2c4de238565468f1.args.minio_password = "SomeSuperPassword1234"
